FROM debian:11-slim

MAINTAINER Yaroslav Stavnichiy <yarosla@gmail.com>

# install requirements
RUN apt-get update \
    && apt-get install -y build-essential autoconf libtool pkg-config && rm -rf /var/lib/apt/lists/*

COPY . /opt/nxweb-src
WORKDIR /opt/nxweb-src

RUN autoreconf --force --install \
    && ./configure \
    && make && make install \
    && cp -aR sample_config/* /srv \
    && tar cfz /opt/nxweb.tar.gz /usr/local/bin/nxweb /usr/local/lib/libnxweb.so* /usr/local/etc/nxweb/nxweb_config.json

# can altrenatively use: checkinstall --fstrans=no --pkgname nxweb --pkgversion 3.3.0-dev
# to create nxweb_3.3.0-dev-1_amd64.deb for further installation

WORKDIR /srv
VOLUME /srv
EXPOSE 80
# CMD ["/bin/bash"]
CMD ["/usr/local/bin/nxweb", "-H", ":80"]
