#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define NXWEB_LISTEN_PORT 8777
#define N_NET_THREADS 4
// N_WORKER_THREADS - number of worker threads per each network thread
#define N_WORKER_THREADS 4
#define NXWEB_KEEP_ALIVE_TIMEOUT 30000000
#define NXWEB_WRITE_TIMEOUT 10000000
#define NXWEB_WRITE_BODY_TIMEOUT 10000000
#define NXWEB_READ_TIMEOUT 10000000
#define NXWEB_READ_BODY_TIMEOUT 120000000
#define NXWEB_MAX_RESPONSE_HEADERS 16
#define REQUEST_CONTENT_SIZE_LIMIT 524288
#define NXWEB_JOBS_QUEUE_SIZE 8192
#define NXWEB_ACCEPT_QUEUE_SIZE 4096
#define NXWEB_PID_FILE "nxweb.pid"

#endif // CONFIG_H_INCLUDED
